[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  version = "~5.6.0"

[[constraint]]
  name = "github.com/blang/semver"
  version = "~3.5.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/emersion/go-imap"
  version = "v1.0.0-beta.1"

[[constraint]]
  name = "github.com/emersion/go-message"
  version = "0.9.1"
